// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// ignore: unused_import
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGgCkQvEq7CgPUn9D_FR0bW4cm0jfrrQQ',
    appId: '1:490196834436:web:b1f69cbbd479951b4a0ad1',
    messagingSenderId: '490196834436',
    projectId: 'project-187165781258254506',
    authDomain: 'project-187165781258254506.firebaseapp.com',
    storageBucket: 'project-187165781258254506.appspot.com',
    measurementId: 'G-Y5HZ487XNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOmEURe2bzPtME9lF-ibOt_cGystVdRMo',
    appId: '1:490196834436:android:3f58e422be28b22d4a0ad1',
    messagingSenderId: '490196834436',
    projectId: 'project-187165781258254506',
    storageBucket: 'project-187165781258254506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0IAfj0V4DKHlMqf7bvKvEq4YCbt_Fv5E',
    appId: '1:490196834436:ios:66ad01c77f817e4c4a0ad1',
    messagingSenderId: '490196834436',
    projectId: 'project-187165781258254506',
    storageBucket: 'project-187165781258254506.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
